
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuthmkhvcajlwjrlnmsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dGhta2h2Y2FqbHdqcmxubXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzUzMDUsImV4cCI6MjA1OTIxMTMwNX0.Q-GSMtDnGpB5tQRc0nWU4AwoMMMNJiZa0a4lia-V7lI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false
    }
  }
);
